In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Chemins des fichiers
DATA_DIR = Path('../data/volleyball')
MYSPORTU_FILE = DATA_DIR / 'volley_mysportu.xlsx'
CONFIG_FILE = DATA_DIR / 'config_volleyP2.xlsx'

print(f"Fichier MySportU existe: {MYSPORTU_FILE.exists()}")
print(f"Fichier Config existe: {CONFIG_FILE.exists()}")

Fichier MySportU existe: True
Fichier Config existe: True

In [2]:
# Charger le fichier MySportU - explorer toutes les feuilles
xl_mysportu = pd.ExcelFile(MYSPORTU_FILE)
print("Feuilles dans MySportU:")
for sheet in xl_mysportu.sheet_names:
    print(f"  - {sheet}")

Feuilles dans MySportU:
  - Sheet1

In [3]:
# Charger le fichier de config - explorer toutes les feuilles
xl_config = pd.ExcelFile(CONFIG_FILE)
print("Feuilles dans config_volleyP2:")
for sheet in xl_config.sheet_names:
    print(f"  - {sheet}")

Feuilles dans config_volleyP2:
  - Equipes
  - Gymnases
  - Indispos_Gymnases
  - Indispos_Equipes
  - Indispos_Institutions
  - Preferences_Gymnases
  - Obligation_Presence
  - Ententes
  - Contraintes_Temporelles
  - _Listes_Validation
  - Types_Poules
  - Equipes_Hors_Championnat
  - Listes_Deroulantes
  - Dispos_Gymnases_Equipes
  - Coach_Groups
  - Groupes_Non_Simultaneite
  - Matchs_Fixes
  - Matchs_Annules

In [4]:
# Explorer chaque feuille de MySportU
for sheet in xl_mysportu.sheet_names:
    df = pd.read_excel(MYSPORTU_FILE, sheet_name=sheet)
    print(f"\n{'='*60}")
    print(f"Feuille: {sheet}")
    print(f"Dimensions: {df.shape}")
    print(f"Colonnes: {list(df.columns)}")
    print(f"\nAperçu:")
    display(df.head(10))

============================================================
Feuille: Sheet1
Dimensions: (280, 11)
Colonnes: ['Discipline', 'Championnat', 'Phase', 'Journée/Tour', 'Date', 'Heure', 'Lieu', 'Equipe A', 'Equipe B', 'Score', 'etat']

Aperçu:

,Discipline,Championnat,Phase,Journée/Tour,Date,Heure,Lieu,Equipe A,Equipe B,Score,etat
0,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,16:15,N-A,06906903102 - IUT Lyon 1 Villeurbanne,00069042006 - IUT St Etienne,NaN,Non joué
1,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,14:45,N-A,06906903107 - IUT Lyon 1 Bourg-en-Bresse,03803800202 - IUT Grenoble,NaN,Non joué
2,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,14:00,N-A,06906903107 - IUT Lyon 1 Bourg-en-Bresse,06906903102 - IUT Lyon 1 Villeurbanne,NaN,Non joué
3,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,14:00,N-A,00069042009 - IUT Roanne,00069042006 - IUT St Etienne,NaN,Non joué
4,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,15:30,N-A,00069042009 - IUT Roanne,06906903107 - IUT Lyon 1 Bourg-en-Bresse,NaN,Non joué
5,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,17:00,N-A,03803800202 - IUT Grenoble,06906903102 - IUT Lyon 1 Villeurbanne,NaN,Non joué
6,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,16:15,N-A,03803800202 - IUT Grenoble,00069042009 - IUT Roanne,NaN,Non joué
7,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,17:00,N-A,00069042006 - IUT St Etienne,06906903107 - IUT Lyon 1 Bourg-en-Bresse,NaN,Non joué
8,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,15:30,N-A,00069042006 - IUT St Etienne,03803800202 - IUT Grenoble,NaN,Non joué
9,Volley 6X6,Championnat Inter-Ligues des IUT de volley Mas...,Phase 1,1,29/01/2026,14:45,N-A,00069042009 - IUT Roanne,06906903102 - IUT Lyon 1 Villeurbanne,NaN,Non joué

In [5]:
# Charger les données MySportU
df_mysportu = pd.read_excel(MYSPORTU_FILE, sheet_name='Sheet1')
print(f"Total matchs MySportU: {len(df_mysportu)}")
print(f"\nChampionnats disponibles:")
for champ in df_mysportu['Championnat'].unique():
    count = len(df_mysportu[df_mysportu['Championnat'] == champ])
    print(f"  - {champ}: {count} matchs")

Total matchs MySportU: 280

Championnats disponibles:
  - Championnat Inter-Ligues des IUT de volley Masculin: 16 matchs
  - Acad VB Féminin Excellence B: 3 matchs
  - LYON VBF PH2 - Championnat Académique de Volley Féminin: 95 matchs
  - Acad VB Masculin Excellence A: 5 matchs
  - Acad VB Masculin Excellence C: 4 matchs
  - Coupe de France des ESC Volley 6X6 Féminin: 2 matchs
  - Coupe de France des ESC Volley 6X6 Masculin: 4 matchs
  - Ligue Universitaire VB F: 6 matchs
  - Ligue Universitaire VB M: 2 matchs
  - STE VBM - Championnat local Universitaire de volley 6X6 Masculin: 10 matchs
  - LYON VBM PH2 - Championnat Académique Volley Masculin: 126 matchs
  - STE VBMX - Championnat local Universitaire de volley 6X6 Mixte: 7 matchs

In [6]:
# Filtrer uniquement les matchs PH2
df_ph2 = df_mysportu[df_mysportu['Championnat'].str.contains('PH2', na=False)].copy()
print(f"Total matchs PH2: {len(df_ph2)}")
print(f"\nRépartition par championnat:")
print(df_ph2['Championnat'].value_counts())

print(f"\nColonnes et types:")
print(df_ph2.dtypes)

print(f"\nAperçu des données PH2:")
df_ph2.head(10)

Total matchs PH2: 221

Répartition par championnat:
Championnat
LYON VBM PH2 - Championnat Académique Volley Masculin      126
LYON VBF PH2 - Championnat Académique de Volley Féminin     95
Name: count, dtype: int64

Colonnes et types:
Discipline      object
Championnat     object
Phase           object
Journée/Tour     int64
Date            object
Heure           object
Lieu            object
Equipe A        object
Equipe B        object
Score           object
etat            object
dtype: object

Aperçu des données PH2:

,Discipline,Championnat,Phase,Journée/Tour,Date,Heure,Lieu,Equipe A,Equipe B,Score,etat
19,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,12/03/2026,14:00,HALLE - C.BESSON,069069031 - LYON 1 (1),069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1,NaN,Non joué
20,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,12/02/2026,16:00,HALLE - C.BESSON,069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2,069069031 - LYON 1 (11),NaN,Non joué
21,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,02/04/2026,18:00,HALLE - 3D,069069020 - ENTPE FIlles,069069018 - EML 1 F VB,NaN,Non joué
22,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,02/04/2026,16:00,HALLE - C.BESSON,069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2,069069031 - LYON 1 (1),NaN,Non joué
23,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,05/02/2026,14:00,HALLE - C.BESSON,069069020 - ENTPE FIlles,069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1,NaN,Non joué
24,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,29/01/2026,18:00,HALLE - C.BESSON,069069031 - LYON 1 (11),069069018 - EML 1 F VB,NaN,Non joué
25,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,19/03/2026,14:00,HALLE - C.BESSON,069069020 - ENTPE FIlles,069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2,NaN,Non joué
26,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,05/02/2026,16:00,HALLE - C.BESSON,069069031 - LYON 1 (11),069069031 - LYON 1 (1),NaN,Non joué
27,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,26/02/2026,18:00,HALLE - C.BESSON,069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1,069069018 - EML 1 F VB,NaN,Non joué
28,Volley 6X6,LYON VBF PH2 - Championnat Académique de Volle...,A1,1,05/03/2026,14:00,HALLE - C.BESSON,069069031 - LYON 1 (11),069069020 - ENTPE FIlles,NaN,Non joué

In [7]:
# Extraire les équipes uniques de MySportU PH2
equipes_mysportu_A = set(df_ph2['Equipe A'].dropna().unique())
equipes_mysportu_B = set(df_ph2['Equipe B'].dropna().unique())
equipes_mysportu = sorted(equipes_mysportu_A | equipes_mysportu_B)

print(f"Équipes uniques MySportU PH2: {len(equipes_mysportu)}")
print("\nListe des équipes:")
for i, eq in enumerate(equipes_mysportu, 1):
    print(f"  {i:2}. {eq}")

Équipes uniques MySportU PH2: 116

Liste des équipes:
   1. 069069001 - ENTPE (1) M
   2. 069069001 - ENTPE (2) M
   3. 069069006 - UDL - UTE LYON 2 VB M 5
   4. 069069006 - UDL UTE LYON 2 IEP VB M 4
   5. 069069006 - UDL UTE LYON 2 VB M 6
   6. 069069006 - UDL- UTE LYON 2 VB F (1)
   7. 069069006 - UDL- UTE LYON 2 VB F (2)
   8. 069069006 - UDL- UTE LYON 2 VB F (3)
   9. 069069006 - UDL- UTE LYON 2 VB F (5)
  10. 069069006 - UDL- UTE LYON 2 VB F (6)
  11. 069069006 - UDL- UTE LYON 2 VB M 1
  12. 069069006 - UDL- UTE LYON 2 VB M 2
  13. 069069006 - UDL- UTE LYON 2 VB M 3
  14. 069069006 - UDL- UTE LYON 2-IEP VB F (4)
  15. 069069006 - UDL-UTE LYON2 VB F (7)
  16. 069069007 - LYON3 (1) Volley Féminin
  17. 069069007 - LYON3 (1) Volley Masculin
  18. 069069007 - LYON3 (2) Volley Féminin
  19. 069069007 - LYON3 (2) Volley masculin
  20. 069069007 - LYON3 (3) Volley Féminin
  21. 069069007 - LYON3 (3) Volley Masculin
  22. 069069007 - LYON3 (5) Volley Masculin
  23. 069069007 - LYON3 (6) Volley Masculin
  24. 069069007 - LYON3(4) Volley Féminin
  25. 069069007 - LYON3(4) Volley Masculin
  26. 069069007 - LYON3(5) Volley Féminin
  27. 069069007 - LYON3(6) Volley Féminin
  28. 069069008 - EMSLB 1
  29. 069069008 - EMSLB 2
  30. 069069008 - ESA VOLLEY MASCULIN 1
  31. 069069009 - ISARA1
  32. 069069009 - ISARA2
  33. 069069012 - CATHO
  34. 069069012 - CATHO (1)
  35. 069069012 - CATHO (2)
  36. 069069014 - CPE
  37. 069069014 - CPE VB M n°1
  38. 069069014 - CPE VB M n°2
  39. 069069015 - AS VOLLEY FEMININ
  40. 069069015 - AS VOLLEY MASCULIN
  41. 069069015 - AS VOLLEY MASCULIN 2
  42. 069069016 - 069069016 CENTRALE LYON VOLLEY F2
  43. 069069016 - 069069016 Centrale Lyon VOLLEY F1
  44. 069069016 - CENTRALE LYON VOLLEY M 1
  45. 069069016 - Centrale Lyon volley M3
  46. 069069016 - Centrale lyon volley M2
  47. 069069018 - EML 1 F VB
  48. 069069018 - EML 1 M VB
  49. 069069018 - EML 2 F VB
  50. 069069018 - EML 2 M VB
  51. 069069019 - ENS VB F1
  52. 069069019 - ENS VB G1
  53. 069069019 - ENS VB G3
  54. 069069020 - ENTPE 2
  55. 069069020 - ENTPE FIlles
  56. 069069021 - Volley Féminin 2
  57. 069069021 - Volley masculin 1
  58. 069069021 - Volley masculin 2
  59. 069069022 - Equipe de volley masculine de l'ESSCA Lyon
  60. 069069022 - Equipe féminine de volley de l'ESSCA Lyon
  61. 069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1
  62. 069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2
  63. 069069025 - AS INSA LYON VOLLEY-BALL FEMININ 3
  64. 069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 1
  65. 069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 2
  66. 069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 3
  67. 069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 4
  68. 069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 5
  69. 069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 6
  70. 069069026 - ISOvolley
  71. 069069028 - COB Volley Féminin 1
  72. 069069028 - COB Volley Masculin 1
  73. 069069029 - CESI (1)
  74. 069069029 - CESI (2)
  75. 069069031 - LYON 1 (1)
  76. 069069031 - LYON 1 (10)
  77. 069069031 - LYON 1 (11)
  78. 069069031 - LYON 1 (12)
  79. 069069031 - LYON 1 (13)
  80. 069069031 - LYON 1 (14)
  81. 069069031 - LYON 1 (15)
  82. 069069031 - LYON 1 (17)
  83. 069069031 - LYON 1 (2)
  84. 069069031 - LYON 1 (26)
  85. 069069031 - LYON 1 (27)
  86. 069069031 - LYON 1 (3)
  87. 069069031 - LYON 1 (4)
  88. 069069031 - LYON 1 (5)
  89. 069069031 - LYON 1 (6)
  90. 069069031 - LYON 1 (7)
  91. 069069031 - LYON 1 (8)
  92. 069069031 - LYON 1(12)
  93. 069069031 - LYON 1(6)
  94. 069069031 - LYON 1(7)
  95. 069069031 - LYON 1(8)
  96. 069069031 - Lyon 1 (10)
  97. 069069031 - Lyon 1 (16)
  98. 069069031 - Lyon 1 (19)
  99. 069069031 - Lyon 1 (20)
  100. 069069031 - Lyon 1 (21)
  101. 069069031 - Lyon 1 (22)
  102. 069069031 - Lyon 1 (23)
  103. 069069031 - Lyon 1 (24)
  104. 069069031 - Lyon 1 (25)
  105. 069069031 - Lyon 1 (9)
  106. 069069031 - Lyon 1 Santé (1)
  107. 069069031 - Lyon 1 Santé (2)
  108. 069069031 - Lyon 1 Santé (3)
  109. 069069031 - Lyon 1 Santé (4)
  110. 069069031 - Lyon 1 Santé (5)
  111. 069069031 - Lyon1Santé(1)
  112. 069069031 - Lyon1Santé(2)
  113. 069069031 - Lyon1Santé(3)
  114. 069069031 - Lyon1Santé(4)
  115. 069069031 - Lyon1Santé(5)
  116. 069069031 - Lyon1Santé(6)

In [8]:
# Charger les équipes de la configuration
df_equipes_config = pd.read_excel(CONFIG_FILE, sheet_name='Equipes')
print(f"Colonnes de la feuille Equipes:")
print(df_equipes_config.columns.tolist())
print(f"\nNombre d'équipes: {len(df_equipes_config)}")
df_equipes_config.head(20)

Colonnes de la feuille Equipes:
['Equipe', 'Niveau_Equipe', 'Genre_Equipe', 'Poule', 'Horaire_Prefere', 'Responsable_Nom', 'Responsable_Email', 'Responsable_Telephone']

Nombre d'équipes: 126

,Equipe,Niveau_Equipe,Genre_Equipe,Poule,Horaire_Prefere,Responsable_Nom,Responsable_Email,Responsable_Telephone
0,LYON 1 (1),A1,F,VBFA1PA,14:00,ROLAND DOMINIQUE,dominique.roland@univ-lyon1.fr,617952934.0
1,ECL (1),A2,F,VBFA2PA,14:00,CHALTON SIMON,simon.chalton@ec-lyon.fr,621239393.0
2,ENTPE (2),A3,F,VBFA3PA,14:00,NaN,NaN,NaN
3,ECL (2),A4,F,VBFA4PA,14:00,CHALTON SIMON,simon.chalton@ec-lyon.fr,621239393.0
4,INSA (2),A1,F,VBFA1PA,14:00,JAUSSAUD Marie,marie.jaussaud@insa-lyon.fr,663913970.0
5,LYON 1 (5),A2,F,VBFA2PA,14:00,ROLAND DOMINIQUE,dominique.roland@univ-lyon1.fr,617952934.0
6,ECAM (1),A3,F,VBFA3PA,16:00,Giral Valentine,valentine.giral@ecam.fr,760397492.0
7,LYON 1 (12),A4,F,VBFA4PA,14:00,MIGNOT EMILIEN,emilien.mignot@univ-lyon1.fr,783463825.0
8,ENTPE (1),A1,F,VBFA1PA,14:00,NaN,NaN,NaN
9,INSA (3),A2,F,VBFA2PA,14:00,JAUSSAUD Marie,marie.jaussaud@insa-lyon.fr,663913970.0
10,LYON 1 (9),A3,F,VBFA3PA,18:00,ROLAND DOMINIQUE,dominique.roland@univ-lyon1.fr,617952934.0
11,LYON 1 (13),A4,F,VBFA4PA,14:00,BOUCHET LEOPOLDINE,leopoldine.bouchet@univ-lyon1.fr,785758187.0
12,INSA (1),A1,F,VBFA1PA,14:00,JAUSSAUD Marie,marie.jaussaud@insa-lyon.fr,663913970.0
13,LYON 2 (6),A2,F,VBFA2PA,20:00,Amin GRAGUEB,amin.gragueb-chatti@univ-lyon2.fr,618457220.0
14,LYON 2 (5),A3,F,VBFA3PA,20:00,Amin GRAGUEB,amin.gragueb-chatti@univ-lyon2.fr,618457220.0
15,LYON 1 (7),A4,F,VBFA4PA,14:00,EVAN FRANCE,france.evan@univ-lyon1.fr,662858903.0
16,LYON 1 (11),A1,F,VBFA1PA,14:00,Bouvier Thierry,thierry.bouvier@univ-lyon1.fr,687072365.0
17,ESSCA (1),A4,F,VBFA4PA,16:00,Feillens Louis,louis.feillens@essca.eu,612532804.0
18,EML (1),A1,F,VBFA1PA,18:00,Blanchard Anne-Cécile,anne-cecile.blanchard@ext.emlyon.com,673873344.0
19,LYON 1 (4),A2,F,VBFA2PB,20:00,ROLAND DOMINIQUE,dominique.roland@univ-lyon1.fr,617952934.0

In [9]:
# Afficher toutes les équipes de la config
equipes_config = df_equipes_config['Equipe'].dropna().tolist()
print(f"Équipes dans la config ({len(equipes_config)}):")
for i, eq in enumerate(sorted(equipes_config), 1):
    print(f"  {i:3}. {eq}")

Équipes dans la config (126):
    1. CATHO (1)
    2. CATHO (1)
    3. CATHO (2)
    4. CESI (1)
    5. CESI (2)
    6. CPE (1)
    7. CPE (1)
    8. CPE (2)
    9. ECAM (1)
   10. ECAM (1)
   11. ECAM (2)
   12. ECL (1)
   13. ECL (1)
   14. ECL (2)
   15. ECL (2)
   16. ECL (3)
   17. EML (1)
   18. EML (1)
   19. EML (2)
   20. EML (2)
   21. ENS (1)
   22. ENS (1)
   23. ENS (3)
   24. ENTPE (1)
   25. ENTPE (1)
   26. ENTPE (2)
   27. ENTPE (2)
   28. ESA (1)
   29. ESA (1)
   30. ESA (2)
   31. ESME (1)
   32. ESME (2)
   33. ESME (2)
   34. ESSCA (1)
   35. ESSCA (1)
   36. INSA (1)
   37. INSA (1)
   38. INSA (2)
   39. INSA (2)
   40. INSA (3)
   41. INSA (3)
   42. INSA (4)
   43. INSA (5)
   44. INSA (6)
   45. ISARA (1)
   46. ISARA (2)
   47. ISOSTEO (1)
   48. ISOSTEO (1)
   49. LYON 1 (1)
   50. LYON 1 (1)
   51. LYON 1 (10)
   52. LYON 1 (10)
   53. LYON 1 (11)
   54. LYON 1 (11)
   55. LYON 1 (12)
   56. LYON 1 (12)
   57. LYON 1 (13)
   58. LYON 1 (13)
   59. LYON 1 (14)
   60. LYON 1 (15)
   61. LYON 1 (16)
   62. LYON 1 (17)
   63. LYON 1 (18)
   64. LYON 1 (19)
   65. LYON 1 (2)
   66. LYON 1 (2)
   67. LYON 1 (20)
   68. LYON 1 (21)
   69. LYON 1 (22)
   70. LYON 1 (23)
   71. LYON 1 (24)
   72. LYON 1 (25)
   73. LYON 1 (26)
   74. LYON 1 (27)
   75. LYON 1 (3)
   76. LYON 1 (3)
   77. LYON 1 (4)
   78. LYON 1 (4)
   79. LYON 1 (5)
   80. LYON 1 (5)
   81. LYON 1 (6)
   82. LYON 1 (6)
   83. LYON 1 (7)
   84. LYON 1 (7)
   85. LYON 1 (8)
   86. LYON 1 (8)
   87. LYON 1 (9)
   88. LYON 1 (9)
   89. LYON 2 (1)
   90. LYON 2 (1)
   91. LYON 2 (2)
   92. LYON 2 (2)
   93. LYON 2 (3)
   94. LYON 2 (3)
   95. LYON 2 (5)
   96. LYON 2 (5)
   97. LYON 2 (6)
   98. LYON 2 (6)
   99. LYON 2 (7)
  100. LYON 2 (IEP) (4)
  101. LYON 2 (IEP) (4)
  102. LYON 3 (1)
  103. LYON 3 (1)
  104. LYON 3 (2)
  105. LYON 3 (2)
  106. LYON 3 (3)
  107. LYON 3 (3)
  108. LYON 3 (4)
  109. LYON 3 (4)
  110. LYON 3 (5)
  111. LYON 3 (5)
  112. LYON 3 (6)
  113. LYON 3 (6)
  114. SANTE (1)
  115. SANTE (1)
  116. SANTE (2)
  117. SANTE (2)
  118. SANTE (3)
  119. SANTE (3)
  120. SANTE (4)
  121. SANTE (4)
  122. SANTE (5)
  123. SANTE (5)
  124. SANTE (6)
  125. VETO (1)
  126. VETO (1)

In [10]:
# Voir les équipes avec leur genre
print("Équipes avec genre dans la config:")
df_equipes_sorted = df_equipes_config[['Equipe', 'Genre_Equipe', 'Poule']].sort_values(['Genre_Equipe', 'Equipe'])
for genre in df_equipes_sorted['Genre_Equipe'].dropna().unique():
    print(f"\n=== {genre} ===")
    eqs = df_equipes_sorted[df_equipes_sorted['Genre_Equipe'] == genre]
    for _, row in eqs.iterrows():
        print(f"  {row['Equipe']} - Poule: {row['Poule']}")

Équipes avec genre dans la config:

=== F ===
  CATHO (1) - Poule: VBFA3PC
  CPE (1) - Poule: VBFA3PB
  ECAM (1) - Poule: VBFA3PA
  ECL (1) - Poule: VBFA2PA
  ECL (2) - Poule: VBFA4PA
  EML (1) - Poule: VBFA1PA
  EML (2) - Poule: VBFA4PC
  ENS (1) - Poule: VBFA2PB
  ENTPE (1) - Poule: VBFA1PA
  ENTPE (2) - Poule: VBFA3PA
  ESA (1) - Poule: VBFA1PB
  ESA (2) - Poule: VBFA4PC
  ESME (2) - Poule: VBFA4PB
  ESSCA (1) - Poule: VBFA4PA
  INSA (1) - Poule: VBFA1PA
  INSA (2) - Poule: VBFA1PA
  INSA (3) - Poule: VBFA2PA
  ISOSTEO (1) - Poule: VBFA4PB
  LYON 1 (1) - Poule: VBFA1PA
  LYON 1 (10) - Poule: VBFA4PB
  LYON 1 (11) - Poule: VBFA1PA
  LYON 1 (12) - Poule: VBFA4PA
  LYON 1 (13) - Poule: VBFA4PA
  LYON 1 (2) - Poule: VBFA2PC
  LYON 1 (3) - Poule: VBFA3PC
  LYON 1 (4) - Poule: VBFA2PB
  LYON 1 (5) - Poule: VBFA2PA
  LYON 1 (6) - Poule: VBFA3PB
  LYON 1 (7) - Poule: VBFA4PA
  LYON 1 (8) - Poule: VBFA4PB
  LYON 1 (9) - Poule: VBFA3PA
  LYON 2 (1) - Poule: VBFA1PB
  LYON 2 (2) - Poule: VBFA1PB
  LYON 2 (3) - Poule: VBFA2PC
  LYON 2 (5) - Poule: VBFA3PA
  LYON 2 (6) - Poule: VBFA2PA
  LYON 2 (7) - Poule: VBFA3PC
  LYON 2 (IEP) (4) - Poule: VBFA3PC
  LYON 3 (1) - Poule: VBFA1PB
  LYON 3 (2) - Poule: VBFA2PC
  LYON 3 (3) - Poule: VBFA2PB
  LYON 3 (4) - Poule: VBFA3PB
  LYON 3 (5) - Poule: VBFA4PC
  LYON 3 (6) - Poule: VBFA4PC
  SANTE (1) - Poule: VBFA1PB
  SANTE (2) - Poule: VBFA2PB
  SANTE (3) - Poule: VBFA3PC
  SANTE (4) - Poule: VBFA3PB
  SANTE (5) - Poule: VBFA3PB
  SANTE (6) - Poule: VBFA4PC
  VETO (1) - Poule: VBFA2PC

=== M ===
  CATHO (1) - Poule: VBMA3PD
  CATHO (2) - Poule: VBMA3PF
  CESI (1) - Poule: VBMA3PD
  CESI (2) - Poule: VBMA3PE
  CPE (1) - Poule: VBMA2PD
  CPE (2) - Poule: VBMA3PB
  ECAM (1) - Poule: VBMA1PC
  ECAM (2) - Poule: VBMA3PE
  ECL (1) - Poule: VBMA2PA
  ECL (2) - Poule: VBMA2PA
  ECL (3) - Poule: VBMA3PA
  EML (1) - Poule: VBMA1PC
  EML (2) - Poule: VBMA3PC
  ENS (1) - Poule: VBMA1PB
  ENS (3) - Poule: VBMA3PC
  ENTPE (1) - Poule: VBMA1PA
  ENTPE (2) - Poule: VBMA2PA
  ESA (1) - Poule: VBMA2PD
  ESME (1) - Poule: VBMA2PC
  ESME (2) - Poule: VBMA4PA
  ESSCA (1) - Poule: VBMA4PB
  INSA (1) - Poule: VBMA1PA
  INSA (2) - Poule: VBMA1PB
  INSA (3) - Poule: VBMA2PA
  INSA (4) - Poule: VBMA2PB
  INSA (5) - Poule: VBMA3PA
  INSA (6) - Poule: VBMA3PA
  ISARA (1) - Poule: VBMA2PB
  ISARA (2) - Poule: VBMA3PB
  ISOSTEO (1) - Poule: VBMA4PB
  LYON 1 (1) - Poule: VBMA1PA
  LYON 1 (10) - Poule: VBMA3PB
  LYON 1 (11) - Poule: VBMA4PB
  LYON 1 (12) - Poule: VBMA3PC
  LYON 1 (13) - Poule: VBMA3PA
  LYON 1 (14) - Poule: VBMA4PA
  LYON 1 (15) - Poule: VBMA3PD
  LYON 1 (16) - Poule: VBMA3PF
  LYON 1 (17) - Poule: VBMA3PE
  LYON 1 (18) - Poule: VBMA4PA
  LYON 1 (19) - Poule: VBMA4PB
  LYON 1 (2) - Poule: VBMA1PB
  LYON 1 (20) - Poule: VBMA4PA
  LYON 1 (21) - Poule: VBMA2PE
  LYON 1 (22) - Poule: VBMA3PD
  LYON 1 (23) - Poule: VBMA4PC
  LYON 1 (24) - Poule: VBMA3PB
  LYON 1 (25) - Poule: VBMA4PB
  LYON 1 (26) - Poule: VBMA1PA
  LYON 1 (27) - Poule: VBMA4PA
  LYON 1 (3) - Poule: VBMA2PB
  LYON 1 (4) - Poule: VBMA2PC
  LYON 1 (5) - Poule: VBMA2PB
  LYON 1 (6) - Poule: VBMA2PC
  LYON 1 (7) - Poule: VBMA2PC
  LYON 1 (8) - Poule: VBMA2PA
  LYON 1 (9) - Poule: VBMA3PA
  LYON 2 (1) - Poule: VBMA1PB
  LYON 2 (2) - Poule: VBMA1PC
  LYON 2 (3) - Poule: VBMA3PD
  LYON 2 (5) - Poule: VBMA4PC
  LYON 2 (6) - Poule: VBMA3PC
  LYON 2 (IEP) (4) - Poule: VBMA2PE
  LYON 3 (1) - Poule: VBMA1PC
  LYON 3 (2) - Poule: VBMA2PD
  LYON 3 (3) - Poule: VBMA2PE
  LYON 3 (4) - Poule: VBMA3PF
  LYON 3 (5) - Poule: VBMA4PC
  LYON 3 (6) - Poule: VBMA4PC
  SANTE (1) - Poule: VBMA2PD
  SANTE (2) - Poule: VBMA2PE
  SANTE (3) - Poule: VBMA3PE
  SANTE (4) - Poule: VBMA3PF
  SANTE (5) - Poule: VBMA4PC
  VETO (1) - Poule: VBMA2PE

In [11]:
# Charger les gymnases de la configuration
df_gymnases_config = pd.read_excel(CONFIG_FILE, sheet_name='Gymnases')
print("Colonnes Gymnases:")
print(df_gymnases_config.columns.tolist())
print(f"\nNombre de gymnases: {len(df_gymnases_config)}")
print("\nGymnases:")
for _, row in df_gymnases_config.iterrows():
    print(f"  {row['Gymnase']}")

Colonnes Gymnases:
['Gymnase', 'Adresse', 'Capacite', 'Creneaux', 'Niveau', 'Genre_Prioritaire']

Nombre de gymnases: 11

Gymnases:
  DESCARTES
  ECL
  ESA
  LYON 2 HC
  LAENNEC
  BESSON
  L. J. HAUT
  ENTPE
  GRENOBLE
  MARSEILLE
  CLERMONT

In [12]:
# Voir les lieux uniques dans MySportU PH2
lieux_mysportu = df_ph2['Lieu'].dropna().unique()
print(f"Lieux uniques MySportU PH2 ({len(lieux_mysportu)}):")
for lieu in sorted(lieux_mysportu):
    count = len(df_ph2[df_ph2['Lieu'] == lieu])
    print(f"  {lieu} ({count} matchs)")

Lieux uniques MySportU PH2 (9):
  CENTRALE (15 matchs)
  COMPET C (HAUT) - LEON JOUHAUX (7 matchs)
  COMPET. LAPLANCHE- R. LISSMANN (1 matchs)
  ENS DESCARTES (7 matchs)
  ESA BRON (4 matchs)
  HALLE - 3D (46 matchs)
  HALLE - C.BESSON (98 matchs)
  HALLE C LYON 2 (23 matchs)
  N-A (20 matchs)

In [13]:
# Charger les matchs fixes de la configuration
df_matchs_fixes = pd.read_excel(CONFIG_FILE, sheet_name='Matchs_Fixes')
print("Colonnes Matchs_Fixes:")
print(df_matchs_fixes.columns.tolist())
print(f"\nNombre de matchs fixes: {len(df_matchs_fixes)}")
print("\nAperçu des matchs fixes:")
df_matchs_fixes.head(20)

Colonnes Matchs_Fixes:
['Equipe_1', 'Equipe_2', 'Genre', 'Poule', 'Semaine', 'Date', 'Horaire', 'Gymnase', 'Score', 'Type_Competition', 'Remarques', 'Arbitres']

Nombre de matchs fixes: 66

Aperçu des matchs fixes:

,Equipe_1,Equipe_2,Genre,Poule,Semaine,Date,Horaire,Gymnase,Score,Type_Competition,Remarques,Arbitres
0,INSA (1),SUD (2),M,NaN,3 (05/02),NaN,15:00,MARSEILLE,NaN,CFE,NaN,NaN
1,EML (1),SUD (1),M,NaN,3 (05/02),NaN,15:00,MARSEILLE,NaN,CFE,NaN,NaN
2,EML (1),SUD (2),F,NaN,3 (05/02),NaN,15:00,MARSEILLE,NaN,CFE,NaN,NaN
3,INPG (1),SUD (1),F,NaN,3 (05/02),NaN,15:00,MARSEILLE,NaN,CFE,NaN,NaN
4,UDL (1),UDL (2),F,NaN,1 (22/01),NaN,14:00,BESSON,NaN,CFU,NaN,NaN
5,UDG (1),UDL (2),F,NaN,4 (12/02),NaN,15:00,GRENOBLE,NaN,CFU,NaN,NaN
6,UDL (1),INSA (1),F,NaN,4 (12/02),NaN,16:00,BESSON,NaN,CFU,NaN,NaN
7,UCA (1),INSA (1),F,NaN,7 (05/03),NaN,15:00,CLERMONT,NaN,CFU,NaN,NaN
8,UDG (1),UDL (1),F,NaN,7 (05/03),NaN,15:00,GRENOBLE,NaN,CFU,NaN,NaN
9,INSA (1),UDL (1),M,NaN,4 (12/02),NaN,14:00,BESSON,NaN,CFU,NaN,NaN
10,UDG (1),INSA (1),M,NaN,7 (05/03),NaN,15:00,GRENOBLE,NaN,CFU,NaN,NaN
11,LYON 2 (1),ESA (1),F,VBFA1PB,1,22/01/26,20:00,BESSON,NaN,Acad,Importé J1 | J1.xlsx,MOMO
12,LYON 3 (2),LYON 2 (3),F,VBFA2PC,1,22/01/26,20:00,LAENNEC,NaN,Acad,Importé J1 | J1.xlsx,PIERARD
13,ENTPE (2),ECAM (1),F,VBFA3PA,1,22/01/26,16:00,LAENNEC,NaN,Acad,Importé J1 | J1.xlsx,DUBUC
14,LYON 2 (IEP) (4),LYON 1 (3),F,VBFA3PC,1,22/01/26,20:00,BESSON,NaN,Acad,Importé J1 | J1.xlsx,DUPUY
15,ISOSTEO (1),LYON 1 (8),F,VBFA4PB,1,22/01/26,18:00,LAENNEC,NaN,Acad,Importé J1 | J1.xlsx,DUBUC
16,LYON 1 (1),ENTPE (1),M,VBMA1PA,1,22/01/26,14:00,BESSON,NaN,Acad,Importé J1 | J1.xlsx,TOUPIE
17,ISARA (1),LYON 1 (3),M,VBMA2PB,1,22/01/26,16:00,BESSON,NaN,Acad,Importé J1 | J1.xlsx,SION
18,LYON 1 (4),LYON 1 (7),M,VBMA2PC,1,22/01/26,18:00,BESSON,NaN,Acad,Importé J1 | J1.xlsx,DELMAS
19,LYON 1 (21),LYON 3 (3),M,VBMA2PE,1,22/01/26,20:00,BESSON,NaN,Acad,Importé J1 | J1.xlsx,DELMAS

In [14]:
# Voir tous les matchs fixes
print("Tous les matchs fixes:")
for i, row in df_matchs_fixes.iterrows():
    print(f"{i+1:2}. {row['Equipe_1']} vs {row['Equipe_2']} ({row['Genre']}) - Semaine {row['Semaine']}, {row['Gymnase']}")

Tous les matchs fixes:
 1. INSA (1) vs SUD (2) (M) - Semaine 3 (05/02), MARSEILLE
 2. EML (1) vs SUD (1) (M) - Semaine 3 (05/02), MARSEILLE
 3. EML (1) vs SUD (2) (F) - Semaine 3 (05/02), MARSEILLE
 4. INPG (1) vs SUD (1) (F) - Semaine 3 (05/02), MARSEILLE
 5. UDL (1) vs UDL (2) (F) - Semaine 1 (22/01), BESSON
 6. UDG (1) vs UDL (2) (F) - Semaine 4 (12/02), GRENOBLE
 7. UDL (1) vs INSA (1) (F) - Semaine 4 (12/02), BESSON
 8. UCA (1) vs INSA (1) (F) - Semaine 7 (05/03), CLERMONT
 9. UDG (1) vs UDL (1) (F) - Semaine 7 (05/03), GRENOBLE
10. INSA (1) vs UDL (1) (M) - Semaine 4 (12/02), BESSON
11. UDG (1) vs INSA (1) (M) - Semaine 7 (05/03), GRENOBLE
12. LYON 2 (1) vs ESA (1) (F) - Semaine 1, BESSON
13. LYON 3 (2) vs LYON 2 (3) (F) - Semaine 1, LAENNEC
14. ENTPE (2) vs ECAM (1) (F) - Semaine 1, LAENNEC
15. LYON 2 (IEP) (4) vs LYON 1 (3) (F) - Semaine 1, BESSON
16. ISOSTEO (1) vs LYON 1 (8) (F) - Semaine 1, LAENNEC
17. LYON 1 (1) vs ENTPE (1) (M) - Semaine 1, BESSON
18. ISARA (1) vs LYON 1 (3) (M) - Semaine 1, BESSON
19. LYON 1 (4) vs LYON 1 (7) (M) - Semaine 1, BESSON
20. LYON 1 (21) vs LYON 3 (3) (M) - Semaine 1, BESSON
21. LYON 1 (10) vs ISARA (2) (M) - Semaine 1, BESSON
22. LYON 1 (15) vs CESI (1) (M) - Semaine 1, BESSON
23. LYON 1 (14) vs LYON 1 (20) (M) - Semaine 1, BESSON
24. INSA (1) vs INSA (2) (F) - Semaine nan, ENTENTE
25. LYON 3 (2) vs SANTE (1) (M) - Semaine nan, ENTENTE
26. LYON 3 (3) vs SANTE (2) (M) - Semaine nan, ENTENTE
27. LYON 3 (4) vs SANTE (4) (M) - Semaine nan, ENTENTE
28. LYON 3 (6) vs SANTE (5) (M) - Semaine nan, ENTENTE
29. LYON 3 (5) vs SANTE (5) (M) - Semaine nan, ENTENTE
30. LYON 3 (5) vs LYON 3 (6) (M) - Semaine nan, ENTENTE
31. SANTE (1) vs LYON 3 (1) (F) - Semaine nan, ENTENTE
32. LYON 2 (1) vs LYON 2 (2) (F) - Semaine nan, ENTENTE
33. LYON 3 (3) vs SANTE (2) (F) - Semaine nan, ENTENTE
34. SANTE (4) vs LYON 3 (4) (F) - Semaine nan, ENTENTE
35. SANTE (4) vs SANTE (5) (F) - Semaine nan, ENTENTE
36. SANTE (5) vs LYON 3 (4) (F) - Semaine nan, ENTENTE
37. LYON 2 (7) vs LYON 2 (IEP) (4) (F) - Semaine nan, ENTENTE
38. LYON 3 (5) vs LYON 3 (6) (F) - Semaine nan, ENTENTE
39. SANTE (6) vs LYON 3 (5) (F) - Semaine nan, ENTENTE
40. SANTE (6) vs LYON 3 (6) (F) - Semaine nan, ENTENTE
41. LYON 3 (1) vs LYON 2 (2) (F) - Semaine nan, LAENNEC
42. EML (1) vs LYON 1 (11) (F) - Semaine 2, BESSON
43. ENTPE (1) vs LYON 1 (1) (F) - Semaine 2, BESSON
44. SANTE (1) vs LYON 2 (2) (F) - Semaine 2, LAENNEC
45. LYON 3 (3) vs ENS (1) (F) - Semaine 2, DESCARTES
46. ENTPE (2) vs LYON 1 (9) (F) - Semaine 2, LAENNEC
47. ECAM (1) vs LYON 2 (5) (F) - Semaine 2, LYON 2 HC
48. SANTE (4) vs LYON 1 (6) (F) - Semaine 2, BESSON
49. SANTE (3) vs CATHO (1) (F) - Semaine 2, L. J. HAUT
50. LYON 1 (7) vs ESSCA (1) (F) - Semaine 2, L. J. HAUT
51. ESME (2) vs ISOSTEO (1) (F) - Semaine 2, L. J. HAUT
52. LYON 1 (8) vs LYON 1 (10) (F) - Semaine 2, BESSON
53. ESA (2) vs SANTE (6) (F) - Semaine 2, ESA
54. LYON 1 (2) vs LYON 2 (1) (M) - Semaine 2, LAENNEC
55. ECAM (1) vs LYON 3 (1) (M) - Semaine 2, LAENNEC
56. EML (1) vs LYON 2 (2) (M) - Semaine 2, BESSON
57. ENTPE (2) vs LYON 1 (8) (M) - Semaine 2, LAENNEC
58. SANTE (2) vs LYON 2 (IEP) (4) (M) - Semaine 2, LYON 2 HC
59. LYON 1 (13) vs LYON 1 (9) (M) - Semaine 2, BESSON
60. LYON 1 (12) vs ENS (3) (M) - Semaine 2, DESCARTES
61. LYON 2 (3) vs CATHO (1) (M) - Semaine 2, LYON 2 HC
62. ECAM (2) vs CESI (2) (M) - Semaine 2, LYON 2 HC
63. SANTE (3) vs LYON 1 (17) (M) - Semaine 2, BESSON
64. LYON 1 (11) vs ISOSTEO (1) (M) - Semaine 2, LAENNEC
65. LYON 1 (25) vs LYON 1 (19) (M) - Semaine 2, BESSON
66. LYON 2 (5) vs LYON 1 (23) (M) - Semaine 2, LYON 2 HC

# Analyse des patterns de noms

## MySportU
Format: `CODE - NOM EQUIPE`
- CODE: `069069XXX` (numéro d'institution)
- NOM: Nom de l'équipe avec genre (F/M) et numéro

## Config
Format: `NOM (NUMERO)`
- NOM: INSA, LYON 1, LYON 2, etc.
- NUMERO: (1), (2), etc.

## Correspondances à établir
1. Équipes : Matcher le nom et le numéro
2. Gymnases : Mapper les noms courts vers les noms longs MySportU

In [15]:
import re

# Analyser les équipes MySportU pour extraire les composants
def parse_mysportu_team(name):
    """Parse un nom d'équipe MySportU pour extraire le code, l'institution et le numéro"""
    # Format: "069069XXX - NOM EQUIPE"
    match = re.match(r'^(\d+)\s*-\s*(.+)$', name)
    if not match:
        return None, name, None, None
    
    code = match.group(1)
    rest = match.group(2).strip()
    
    # Déterminer le genre (F ou M)
    genre = None
    if 'Féminin' in rest or ' F ' in rest or ' F(' in rest or rest.endswith(' F') or 'F VB' in rest or 'VB F' in rest or 'FILLES' in rest.upper():
        genre = 'F'
    elif 'Masculin' in rest or ' M ' in rest or ' M(' in rest or rest.endswith(' M') or 'M VB' in rest or 'VB M' in rest:
        genre = 'M'
    
    # Extraire le numéro d'équipe
    num_match = re.search(r'[\(\s](\d+)[\)\s]?|(\d+)\s*$|n°(\d+)', rest)
    numero = None
    if num_match:
        numero = num_match.group(1) or num_match.group(2) or num_match.group(3)
    
    return code, rest, genre, numero

# Tester sur quelques équipes
print("Analyse des équipes MySportU:")
for eq in equipes_mysportu[:20]:
    code, name, genre, num = parse_mysportu_team(eq)
    print(f"  {eq}")
    print(f"    -> Code: {code}, Genre: {genre}, Num: {num}")

Analyse des équipes MySportU:
  069069001 - ENTPE (1) M
    -> Code: 069069001, Genre: M, Num: 1
  069069001 - ENTPE (2) M
    -> Code: 069069001, Genre: M, Num: 2
  069069006 - UDL - UTE LYON 2 VB M 5
    -> Code: 069069006, Genre: M, Num: 2
  069069006 - UDL UTE LYON 2 IEP VB M 4
    -> Code: 069069006, Genre: M, Num: 2
  069069006 - UDL UTE LYON 2 VB M 6
    -> Code: 069069006, Genre: M, Num: 2
  069069006 - UDL- UTE LYON 2 VB F (1)
    -> Code: 069069006, Genre: F, Num: 2
  069069006 - UDL- UTE LYON 2 VB F (2)
    -> Code: 069069006, Genre: F, Num: 2
  069069006 - UDL- UTE LYON 2 VB F (3)
    -> Code: 069069006, Genre: F, Num: 2
  069069006 - UDL- UTE LYON 2 VB F (5)
    -> Code: 069069006, Genre: F, Num: 2
  069069006 - UDL- UTE LYON 2 VB F (6)
    -> Code: 069069006, Genre: F, Num: 2
  069069006 - UDL- UTE LYON 2 VB M 1
    -> Code: 069069006, Genre: M, Num: 2
  069069006 - UDL- UTE LYON 2 VB M 2
    -> Code: 069069006, Genre: M, Num: 2
  069069006 - UDL- UTE LYON 2 VB M 3
    -> Code: 069069006, Genre: M, Num: 2
  069069006 - UDL- UTE LYON 2-IEP VB F (4)
    -> Code: 069069006, Genre: F, Num: 2
  069069006 - UDL-UTE LYON2 VB F (7)
    -> Code: 069069006, Genre: F, Num: 7
  069069007 - LYON3 (1) Volley Féminin
    -> Code: 069069007, Genre: F, Num: 1
  069069007 - LYON3 (1) Volley Masculin
    -> Code: 069069007, Genre: M, Num: 1
  069069007 - LYON3 (2) Volley Féminin
    -> Code: 069069007, Genre: F, Num: 2
  069069007 - LYON3 (2) Volley masculin
    -> Code: 069069007, Genre: None, Num: 2
  069069007 - LYON3 (3) Volley Féminin
    -> Code: 069069007, Genre: F, Num: 3

In [16]:
def parse_mysportu_team_v2(name):
    """Parse un nom d'équipe MySportU pour extraire le code, l'institution et le numéro"""
    # Format: "069069XXX - NOM EQUIPE"
    match = re.match(r'^(\d+)\s*-\s*(.+)$', name)
    if not match:
        return None, name, None, None
    
    code = match.group(1)
    rest = match.group(2).strip()
    
    # Déterminer le genre (F ou M)
    genre = None
    rest_upper = rest.upper()
    if 'FÉMININ' in rest_upper or 'FEMININ' in rest_upper or 'FILLES' in rest_upper or ' F ' in rest_upper or ' F(' in rest_upper or rest_upper.endswith(' F') or 'F VB' in rest_upper or 'VB F' in rest_upper:
        genre = 'F'
    elif 'MASCULIN' in rest_upper or ' M ' in rest_upper or ' M(' in rest_upper or rest_upper.endswith(' M') or 'M VB' in rest_upper or 'VB M' in rest_upper:
        genre = 'M'
    
    # Extraire le numéro d'équipe - chercher le pattern (N) ou N à la fin après le genre ou "n°N"
    # Priorité: (N) dans le nom de l'équipe elle-même
    num_match = re.search(r'\((\d+)\)', rest)  # (N)
    if num_match:
        numero = num_match.group(1)
    else:
        # Chercher le numéro à la fin: "VB M 5" ou "n°1"
        num_match = re.search(r'n°(\d+)|VB\s*[MF]\s*(\d+)\s*$|\s(\d+)\s*$', rest)
        numero = None
        if num_match:
            numero = num_match.group(1) or num_match.group(2) or num_match.group(3)
    
    return code, rest, genre, numero

# Tester sur toutes les équipes pour voir les patterns
print("Analyse des équipes MySportU:")
parsed_teams = []
for eq in equipes_mysportu:
    code, name, genre, num = parse_mysportu_team_v2(eq)
    parsed_teams.append({'original': eq, 'code': code, 'name': name, 'genre': genre, 'num': num})
    
df_parsed = pd.DataFrame(parsed_teams)
print(f"\nÉquipes sans genre détecté: {len(df_parsed[df_parsed['genre'].isna()])}")
print(df_parsed[df_parsed['genre'].isna()]['original'].tolist())

print(f"\nÉquipes sans numéro détecté: {len(df_parsed[df_parsed['num'].isna()])}")
print(df_parsed[df_parsed['num'].isna()]['original'].tolist())

Analyse des équipes MySportU:

Équipes sans genre détecté: 60
['069069008 - EMSLB 1', '069069008 - EMSLB 2', '069069009 - ISARA1', '069069009 - ISARA2', '069069012 - CATHO', '069069012 - CATHO (1)', '069069012 - CATHO (2)', '069069014 - CPE', '069069016 - 069069016 CENTRALE LYON VOLLEY F2', '069069016 - 069069016 Centrale Lyon VOLLEY F1', '069069016 - Centrale Lyon volley M3', '069069016 - Centrale lyon volley M2', '069069019 - ENS VB G1', '069069019 - ENS VB G3', '069069020 - ENTPE 2', '069069026 - ISOvolley', '069069029 - CESI (1)', '069069029 - CESI (2)', '069069031 - LYON 1 (1)', '069069031 - LYON 1 (10)', '069069031 - LYON 1 (11)', '069069031 - LYON 1 (12)', '069069031 - LYON 1 (13)', '069069031 - LYON 1 (14)', '069069031 - LYON 1 (15)', '069069031 - LYON 1 (17)', '069069031 - LYON 1 (2)', '069069031 - LYON 1 (26)', '069069031 - LYON 1 (27)', '069069031 - LYON 1 (3)', '069069031 - LYON 1 (4)', '069069031 - LYON 1 (5)', '069069031 - LYON 1 (6)', '069069031 - LYON 1 (7)', '069069031 - LYON 1 (8)', '069069031 - LYON 1(12)', '069069031 - LYON 1(6)', '069069031 - LYON 1(7)', '069069031 - LYON 1(8)', '069069031 - Lyon 1 (10)', '069069031 - Lyon 1 (16)', '069069031 - Lyon 1 (19)', '069069031 - Lyon 1 (20)', '069069031 - Lyon 1 (21)', '069069031 - Lyon 1 (22)', '069069031 - Lyon 1 (23)', '069069031 - Lyon 1 (24)', '069069031 - Lyon 1 (25)', '069069031 - Lyon 1 (9)', '069069031 - Lyon 1 Santé (1)', '069069031 - Lyon 1 Santé (2)', '069069031 - Lyon 1 Santé (3)', '069069031 - Lyon 1 Santé (4)', '069069031 - Lyon 1 Santé (5)', '069069031 - Lyon1Santé(1)', '069069031 - Lyon1Santé(2)', '069069031 - Lyon1Santé(3)', '069069031 - Lyon1Santé(4)', '069069031 - Lyon1Santé(5)', '069069031 - Lyon1Santé(6)']

Équipes sans numéro détecté: 20
['069069009 - ISARA1', '069069009 - ISARA2', '069069012 - CATHO', '069069014 - CPE', '069069015 - AS VOLLEY FEMININ', '069069015 - AS VOLLEY MASCULIN', '069069016 - 069069016 CENTRALE LYON VOLLEY F2', '069069016 - 069069016 Centrale Lyon VOLLEY F1', '069069016 - Centrale Lyon volley M3', '069069016 - Centrale lyon volley M2', '069069018 - EML 1 F VB', '069069018 - EML 1 M VB', '069069018 - EML 2 F VB', '069069018 - EML 2 M VB', '069069019 - ENS VB G1', '069069019 - ENS VB G3', '069069020 - ENTPE FIlles', "069069022 - Equipe de volley masculine de l'ESSCA Lyon", "069069022 - Equipe féminine de volley de l'ESSCA Lyon", '069069026 - ISOvolley']

In [17]:
# Mapping des codes institution vers noms courts
INSTITUTION_CODE_MAP = {
    '069069001': 'ENTPE',   # Attention: doublon avec 069069020
    '069069006': 'LYON 2',
    '069069007': 'LYON 3',
    '069069008': 'ESA',     # EMSLB = ESA Lyon Bron
    '069069009': 'ISARA',
    '069069012': 'CATHO',
    '069069014': 'CPE',
    '069069015': 'ECAM',    # AS = ECAM
    '069069016': 'ECL',     # Centrale Lyon
    '069069018': 'EML',     # EM Lyon
    '069069019': 'ENS',
    '069069020': 'ENTPE',   # ENTPE aussi
    '069069021': 'ESME',    # ESME ?
    '069069022': 'ESSCA',
    '069069025': 'INSA',
    '069069026': 'ISOSTEO',
    '069069028': 'VETO',    # COB = Vétérinaire ?
    '069069029': 'CESI',
    '069069031': 'LYON 1',
}

# Voir les codes uniques dans MySportU
codes_mysportu = df_parsed['code'].dropna().unique()
print("Codes institution MySportU:")
for code in sorted(codes_mysportu):
    eqs = df_parsed[df_parsed['code'] == code]['original'].tolist()
    print(f"\n{code}:")
    for eq in eqs:
        print(f"  {eq}")

Codes institution MySportU:

069069001:
  069069001 - ENTPE (1) M
  069069001 - ENTPE (2) M

069069006:
  069069006 - UDL - UTE LYON 2 VB M 5
  069069006 - UDL UTE LYON 2 IEP VB M 4
  069069006 - UDL UTE LYON 2 VB M 6
  069069006 - UDL- UTE LYON 2 VB F (1)
  069069006 - UDL- UTE LYON 2 VB F (2)
  069069006 - UDL- UTE LYON 2 VB F (3)
  069069006 - UDL- UTE LYON 2 VB F (5)
  069069006 - UDL- UTE LYON 2 VB F (6)
  069069006 - UDL- UTE LYON 2 VB M 1
  069069006 - UDL- UTE LYON 2 VB M 2
  069069006 - UDL- UTE LYON 2 VB M 3
  069069006 - UDL- UTE LYON 2-IEP VB F (4)
  069069006 - UDL-UTE LYON2 VB F (7)

069069007:
  069069007 - LYON3 (1) Volley Féminin
  069069007 - LYON3 (1) Volley Masculin
  069069007 - LYON3 (2) Volley Féminin
  069069007 - LYON3 (2) Volley masculin
  069069007 - LYON3 (3) Volley Féminin
  069069007 - LYON3 (3) Volley Masculin
  069069007 - LYON3 (5) Volley Masculin
  069069007 - LYON3 (6) Volley Masculin
  069069007 - LYON3(4) Volley Féminin
  069069007 - LYON3(4) Volley Masculin
  069069007 - LYON3(5) Volley Féminin
  069069007 - LYON3(6) Volley Féminin

069069008:
  069069008 - EMSLB 1
  069069008 - EMSLB 2
  069069008 - ESA VOLLEY MASCULIN 1

069069009:
  069069009 - ISARA1
  069069009 - ISARA2

069069012:
  069069012 - CATHO
  069069012 - CATHO (1)
  069069012 - CATHO (2)

069069014:
  069069014 - CPE
  069069014 - CPE VB M n°1
  069069014 - CPE VB M n°2

069069015:
  069069015 - AS VOLLEY FEMININ
  069069015 - AS VOLLEY MASCULIN
  069069015 - AS VOLLEY MASCULIN 2

069069016:
  069069016 - 069069016 CENTRALE LYON VOLLEY F2
  069069016 - 069069016 Centrale Lyon VOLLEY F1
  069069016 - CENTRALE LYON VOLLEY M 1
  069069016 - Centrale Lyon volley M3
  069069016 - Centrale lyon volley M2

069069018:
  069069018 - EML 1 F VB
  069069018 - EML 1 M VB
  069069018 - EML 2 F VB
  069069018 - EML 2 M VB

069069019:
  069069019 - ENS VB F1
  069069019 - ENS VB G1
  069069019 - ENS VB G3

069069020:
  069069020 - ENTPE 2
  069069020 - ENTPE FIlles

069069021:
  069069021 - Volley Féminin 2
  069069021 - Volley masculin 1
  069069021 - Volley masculin 2

069069022:
  069069022 - Equipe de volley masculine de l'ESSCA Lyon
  069069022 - Equipe féminine de volley de l'ESSCA Lyon

069069025:
  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1
  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2
  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 3
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 1
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 2
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 3
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 4
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 5
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 6

069069026:
  069069026 - ISOvolley

069069028:
  069069028 - COB Volley Féminin 1
  069069028 - COB Volley Masculin 1

069069029:
  069069029 - CESI (1)
  069069029 - CESI (2)

069069031:
  069069031 - LYON 1 (1)
  069069031 - LYON 1 (10)
  069069031 - LYON 1 (11)
  069069031 - LYON 1 (12)
  069069031 - LYON 1 (13)
  069069031 - LYON 1 (14)
  069069031 - LYON 1 (15)
  069069031 - LYON 1 (17)
  069069031 - LYON 1 (2)
  069069031 - LYON 1 (26)
  069069031 - LYON 1 (27)
  069069031 - LYON 1 (3)
  069069031 - LYON 1 (4)
  069069031 - LYON 1 (5)
  069069031 - LYON 1 (6)
  069069031 - LYON 1 (7)
  069069031 - LYON 1 (8)
  069069031 - LYON 1(12)
  069069031 - LYON 1(6)
  069069031 - LYON 1(7)
  069069031 - LYON 1(8)
  069069031 - Lyon 1 (10)
  069069031 - Lyon 1 (16)
  069069031 - Lyon 1 (19)
  069069031 - Lyon 1 (20)
  069069031 - Lyon 1 (21)
  069069031 - Lyon 1 (22)
  069069031 - Lyon 1 (23)
  069069031 - Lyon 1 (24)
  069069031 - Lyon 1 (25)
  069069031 - Lyon 1 (9)
  069069031 - Lyon 1 Santé (1)
  069069031 - Lyon 1 Santé (2)
  069069031 - Lyon 1 Santé (3)
  069069031 - Lyon 1 Santé (4)
  069069031 - Lyon 1 Santé (5)
  069069031 - Lyon1Santé(1)
  069069031 - Lyon1Santé(2)
  069069031 - Lyon1Santé(3)
  069069031 - Lyon1Santé(4)
  069069031 - Lyon1Santé(5)
  069069031 - Lyon1Santé(6)

In [18]:
# Créer un mapping complet MySportU -> Config
# On va créer une table de correspondance basée sur:
# 1. Le code institution
# 2. Le genre (F/M)
# 3. Le numéro d'équipe

# D'abord, construisons le mapping institution
INSTITUTION_CODE_MAP = {
    '069069001': 'ENTPE',   # Attention: équipes masc seulement ici?
    '069069006': 'LYON 2',
    '069069007': 'LYON 3',
    '069069008': 'ESA',     # EMSLB = ESA Lyon Bron  
    '069069009': 'ISARA',
    '069069012': 'CATHO',
    '069069014': 'CPE',
    '069069015': 'ECAM',    # AS = ECAM
    '069069016': 'ECL',     # Centrale Lyon
    '069069018': 'EML',     # EM Lyon
    '069069019': 'ENS',
    '069069020': 'ENTPE',   # ENTPE aussi (fem + masc 2)
    '069069021': 'ESME',    # Volley masc/fem
    '069069022': 'ESSCA',
    '069069025': 'INSA',
    '069069026': 'ISOSTEO',
    '069069028': 'VETO',    # COB = Vétérinaire
    '069069029': 'CESI',
    '069069031': 'LYON 1',  # inclut SANTE (Lyon 1 Santé)
}

def normalize_mysportu_team(name, genre_from_match=None):
    """
    Normalise un nom d'équipe MySportU vers le format de config.
    
    Args:
        name: Nom brut MySportU (ex: "069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 3")
        genre_from_match: Genre déduit du championnat (F/M) si disponible
    
    Returns:
        (config_name, genre, numero): Tuple avec le nom config, le genre et le numéro
    """
    # Extraire le code et le reste
    match = re.match(r'^(\d+)\s*-\s*(.+)$', name)
    if not match:
        return None, None, None
    
    code = match.group(1)
    rest = match.group(2).strip()
    
    # Obtenir l'institution
    institution = INSTITUTION_CODE_MAP.get(code)
    if not institution:
        return None, None, None
    
    # Déterminer le genre
    rest_upper = rest.upper()
    genre = None
    if 'FÉMININ' in rest_upper or 'FEMININ' in rest_upper or 'FILLES' in rest_upper or \
       ' F ' in rest or ' F(' in rest or rest.endswith(' F') or \
       'F VB' in rest_upper or 'VB F' in rest_upper or ' F1' in rest_upper or ' F2' in rest_upper or ' F3' in rest_upper:
        genre = 'F'
    elif 'MASCULIN' in rest_upper or ' M ' in rest or ' M(' in rest or rest.endswith(' M') or \
         'M VB' in rest_upper or 'VB M' in rest_upper or 'VB G' in rest_upper or \
         ') M' in rest_upper or 'M 1' in rest_upper or 'M 2' in rest_upper or 'M 3' in rest_upper:
        genre = 'M'
    
    # Si pas de genre trouvé, utiliser celui du match
    if genre is None and genre_from_match:
        genre = genre_from_match
    
    # Extraire le numéro
    numero = None
    
    # Cas spéciaux selon l'institution
    if institution == 'LYON 2':
        # Format: UDL- UTE LYON 2 VB F (3) ou UDL UTE LYON 2 VB M 5 ou IEP
        if 'IEP' in rest_upper:
            # C'est LYON 2 (IEP) (4)
            num_match = re.search(r'[MF]\s*(\d+)|(\d+)\s*$', rest)
            if num_match:
                numero = num_match.group(1) or num_match.group(2)
            return 'LYON 2 (IEP) (4)', genre, numero or '4'
        num_match = re.search(r'\((\d+)\)|VB\s*[MF]\s*(\d+)', rest)
        if num_match:
            numero = num_match.group(1) or num_match.group(2)
    
    elif institution == 'LYON 1':
        # Vérifier si c'est SANTE
        if 'SANTÉ' in rest_upper or 'SANTE' in rest_upper:
            num_match = re.search(r'\((\d+)\)|Santé\s*\((\d+)\)|Santé(\d+)', rest, re.IGNORECASE)
            if num_match:
                numero = num_match.group(1) or num_match.group(2) or num_match.group(3)
            return f'SANTE ({numero or "1"})', genre, numero
        # Lyon 1 normal
        num_match = re.search(r'\((\d+)\)|LYON\s*1\s*\((\d+)\)', rest, re.IGNORECASE)
        if num_match:
            numero = num_match.group(1) or num_match.group(2)
    
    elif institution == 'INSA':
        num_match = re.search(r'(\d+)\s*$', rest)
        if num_match:
            numero = num_match.group(1)
    
    elif institution == 'ECL':
        # Format: CENTRALE LYON VOLLEY M 1 ou F1/F2
        num_match = re.search(r'[MF]\s*(\d+)|([MF])(\d+)', rest, re.IGNORECASE)
        if num_match:
            numero = num_match.group(1) or num_match.group(3)
    
    elif institution == 'EML':
        # Format: EML 1 F VB
        num_match = re.search(r'EML\s*(\d+)', rest)
        if num_match:
            numero = num_match.group(1)
    
    elif institution == 'ENS':
        # Format: ENS VB F1 ou ENS VB G1 (G = garçon = M)
        num_match = re.search(r'[FG](\d+)', rest)
        if num_match:
            numero = num_match.group(1)
        if 'VB G' in rest_upper:
            genre = 'M'
    
    elif institution == 'ENTPE':
        # Peut être 069069001 ou 069069020
        if 'FILLES' in rest_upper:
            genre = 'F'
            numero = '1'
        else:
            num_match = re.search(r'\((\d+)\)|ENTPE\s*(\d+)', rest)
            if num_match:
                numero = num_match.group(1) or num_match.group(2)
    
    elif institution == 'ESA':
        # EMSLB ou ESA VOLLEY
        num_match = re.search(r'(\d+)\s*$', rest)
        if num_match:
            numero = num_match.group(1)
    
    elif institution == 'ESME':
        # Volley masculin 1/2 ou Volley Féminin 2
        num_match = re.search(r'(\d+)\s*$', rest)
        if num_match:
            numero = num_match.group(1)
    
    elif institution == 'ESSCA':
        numero = '1'  # Une seule équipe par genre
    
    elif institution == 'CPE':
        # CPE ou CPE VB M n°1/2
        num_match = re.search(r'n°(\d+)|\((\d+)\)', rest)
        if num_match:
            numero = num_match.group(1) or num_match.group(2)
        else:
            numero = '1'  # CPE seul = équipe 1
    
    elif institution == 'CATHO':
        num_match = re.search(r'\((\d+)\)', rest)
        if num_match:
            numero = num_match.group(1)
        else:
            numero = '1'  # CATHO seul = équipe 1
    
    else:
        # Cas général: chercher (N) ou N à la fin
        num_match = re.search(r'\((\d+)\)|(\d+)\s*$', rest)
        if num_match:
            numero = num_match.group(1) or num_match.group(2)
    
    if numero:
        config_name = f"{institution} ({numero})"
    else:
        config_name = f"{institution} (1)"  # Default
    
    return config_name, genre, numero

# Tester la fonction sur quelques équipes
test_teams = [
    '069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 3',
    '069069006 - UDL- UTE LYON 2 VB F (3)',
    '069069031 - Lyon 1 Santé (2)',
    '069069007 - LYON3 (2) Volley Féminin',
    '069069016 - CENTRALE LYON VOLLEY M 1',
    '069069018 - EML 2 F VB',
    '069069019 - ENS VB G3',
    '069069020 - ENTPE FIlles',
    '069069014 - CPE VB M n°2',
    '069069022 - Equipe féminine de volley de l\'ESSCA Lyon',
]

print("Test de normalisation:")
for team in test_teams:
    config_name, genre, num = normalize_mysportu_team(team)
    print(f"  {team}")
    print(f"    -> {config_name} ({genre})")

Test de normalisation:
  069069025 - AS INSA LYON VOLLEY-BALL MASCULIN 3
    -> INSA (3) (M)
  069069006 - UDL- UTE LYON 2 VB F (3)
    -> LYON 2 (3) (F)
  069069031 - Lyon 1 Santé (2)
    -> SANTE (2) (None)
  069069007 - LYON3 (2) Volley Féminin
    -> LYON 3 (2) (F)
  069069016 - CENTRALE LYON VOLLEY M 1
    -> ECL (1) (M)
  069069018 - EML 2 F VB
    -> EML (2) (F)
  069069019 - ENS VB G3
    -> ENS (3) (M)
  069069020 - ENTPE FIlles
    -> ENTPE (1) (F)
  069069014 - CPE VB M n°2
    -> CPE (2) (M)
  069069022 - Equipe féminine de volley de l'ESSCA Lyon
    -> ESSCA (1) (F)

In [19]:
# Créer la table de mapping pour toutes les équipes
mapping_results = []

for eq in equipes_mysportu:
    config_name, genre, num = normalize_mysportu_team(eq)
    mapping_results.append({
        'mysportu_name': eq,
        'config_name': config_name,
        'genre_detected': genre,
        'numero': num
    })

df_mapping = pd.DataFrame(mapping_results)

# Comparer avec les équipes de la config
equipes_config_uniques = set()
for _, row in df_equipes_config.iterrows():
    key = (row['Equipe'], row['Genre_Equipe'])
    equipes_config_uniques.add(key)

print(f"Équipes config uniques: {len(equipes_config_uniques)}")
print(f"Équipes MySportU mappées: {len(df_mapping)}")

# Vérifier les mappings qui n'existent pas dans la config
print("\n=== Équipes MySportU dont le mapping n'existe pas dans la config ===")
problemes = []
for _, row in df_mapping.iterrows():
    key = (row['config_name'], row['genre_detected'])
    if key not in equipes_config_uniques and row['config_name'] is not None:
        problemes.append(row)
        print(f"  {row['mysportu_name']} -> {row['config_name']} ({row['genre_detected']})")

print(f"\nTotal problèmes: {len(problemes)}")

Équipes config uniques: 126
Équipes MySportU mappées: 116

=== Équipes MySportU dont le mapping n'existe pas dans la config ===
  069069008 - EMSLB 1 -> ESA (1) (None)
  069069008 - EMSLB 2 -> ESA (2) (None)
  069069009 - ISARA1 -> ISARA (1) (None)
  069069009 - ISARA2 -> ISARA (2) (None)
  069069012 - CATHO -> CATHO (1) (None)
  069069012 - CATHO (1) -> CATHO (1) (None)
  069069012 - CATHO (2) -> CATHO (2) (None)
  069069014 - CPE -> CPE (1) (None)
  069069016 - Centrale Lyon volley M3 -> ECL (3) (None)
  069069016 - Centrale lyon volley M2 -> ECL (2) (None)
  069069020 - ENTPE 2 -> ENTPE (2) (None)
  069069026 - ISOvolley -> ISOSTEO (1) (None)
  069069029 - CESI (1) -> CESI (1) (None)
  069069029 - CESI (2) -> CESI (2) (None)
  069069031 - LYON 1 (1) -> LYON 1 (1) (None)
  069069031 - LYON 1 (10) -> LYON 1 (10) (None)
  069069031 - LYON 1 (11) -> LYON 1 (11) (None)
  069069031 - LYON 1 (12) -> LYON 1 (12) (None)
  069069031 - LYON 1 (13) -> LYON 1 (13) (None)
  069069031 - LYON 1 (14) -> LYON 1 (14) (None)
  069069031 - LYON 1 (15) -> LYON 1 (15) (None)
  069069031 - LYON 1 (17) -> LYON 1 (17) (None)
  069069031 - LYON 1 (2) -> LYON 1 (2) (None)
  069069031 - LYON 1 (26) -> LYON 1 (26) (None)
  069069031 - LYON 1 (27) -> LYON 1 (27) (None)
  069069031 - LYON 1 (3) -> LYON 1 (3) (None)
  069069031 - LYON 1 (4) -> LYON 1 (4) (None)
  069069031 - LYON 1 (5) -> LYON 1 (5) (None)
  069069031 - LYON 1 (6) -> LYON 1 (6) (None)
  069069031 - LYON 1 (7) -> LYON 1 (7) (None)
  069069031 - LYON 1 (8) -> LYON 1 (8) (None)
  069069031 - LYON 1(12) -> LYON 1 (12) (None)
  069069031 - LYON 1(6) -> LYON 1 (6) (None)
  069069031 - LYON 1(7) -> LYON 1 (7) (None)
  069069031 - LYON 1(8) -> LYON 1 (8) (None)
  069069031 - Lyon 1 (10) -> LYON 1 (10) (None)
  069069031 - Lyon 1 (16) -> LYON 1 (16) (None)
  069069031 - Lyon 1 (19) -> LYON 1 (19) (None)
  069069031 - Lyon 1 (20) -> LYON 1 (20) (None)
  069069031 - Lyon 1 (21) -> LYON 1 (21) (None)
  069069031 - Lyon 1 (22) -> LYON 1 (22) (None)
  069069031 - Lyon 1 (23) -> LYON 1 (23) (None)
  069069031 - Lyon 1 (24) -> LYON 1 (24) (None)
  069069031 - Lyon 1 (25) -> LYON 1 (25) (None)
  069069031 - Lyon 1 (9) -> LYON 1 (9) (None)
  069069031 - Lyon 1 Santé (1) -> SANTE (1) (None)
  069069031 - Lyon 1 Santé (2) -> SANTE (2) (None)
  069069031 - Lyon 1 Santé (3) -> SANTE (3) (None)
  069069031 - Lyon 1 Santé (4) -> SANTE (4) (None)
  069069031 - Lyon 1 Santé (5) -> SANTE (5) (None)
  069069031 - Lyon1Santé(1) -> SANTE (1) (None)
  069069031 - Lyon1Santé(2) -> SANTE (2) (None)
  069069031 - Lyon1Santé(3) -> SANTE (3) (None)
  069069031 - Lyon1Santé(4) -> SANTE (4) (None)
  069069031 - Lyon1Santé(5) -> SANTE (5) (None)
  069069031 - Lyon1Santé(6) -> SANTE (6) (None)

Total problèmes: 56

In [20]:
# Le genre peut être déduit du championnat
# LYON VBF PH2 = Féminin
# LYON VBM PH2 = Masculin

# Créer un mapping équipe -> genre basé sur les matchs
def get_genre_from_championnat(champ):
    if 'VBF' in champ or 'Féminin' in champ:
        return 'F'
    elif 'VBM' in champ or 'Masculin' in champ:
        return 'M'
    return None

# Pour chaque équipe MySportU, trouver le genre via les matchs
equipe_genre_map = {}
for _, row in df_ph2.iterrows():
    genre = get_genre_from_championnat(row['Championnat'])
    if genre:
        equipe_genre_map[row['Equipe A']] = genre
        equipe_genre_map[row['Equipe B']] = genre

print(f"Équipes avec genre déduit du championnat: {len(equipe_genre_map)}")

# Maintenant refaire le mapping avec le genre
mapping_results_v2 = []
for eq in equipes_mysportu:
    genre_from_champ = equipe_genre_map.get(eq)
    config_name, genre_detected, num = normalize_mysportu_team(eq, genre_from_champ)
    final_genre = genre_detected or genre_from_champ
    mapping_results_v2.append({
        'mysportu_name': eq,
        'config_name': config_name,
        'genre': final_genre,
        'numero': num
    })

df_mapping_v2 = pd.DataFrame(mapping_results_v2)

# Vérifier à nouveau
print("\n=== Équipes MySportU dont le mapping n'existe pas dans la config (v2) ===")
problemes_v2 = []
for _, row in df_mapping_v2.iterrows():
    key = (row['config_name'], row['genre'])
    if key not in equipes_config_uniques and row['config_name'] is not None:
        problemes_v2.append(row)
        print(f"  {row['mysportu_name']} -> {row['config_name']} ({row['genre']})")

print(f"\nTotal problèmes: {len(problemes_v2)}")

Équipes avec genre déduit du championnat: 116

=== Équipes MySportU dont le mapping n'existe pas dans la config (v2) ===

Total problèmes: 0

In [21]:
# Mapping des gymnases
# MySportU -> Config
print("=== Mapping des gymnases ===")
print("\nGymnases MySportU:")
for lieu in sorted(lieux_mysportu):
    print(f"  {lieu}")
    
print("\nGymnases Config:")
for gym in df_gymnases_config['Gymnase'].tolist():
    print(f"  {gym}")

# Créer le mapping (corrigé)
GYMNASE_MAP = {
    'CENTRALE': 'ECL',
    'COMPET C (HAUT) - LEON JOUHAUX': 'L. J. HAUT',
    'COMPET. LAPLANCHE- R. LISSMANN': None,  # Non mappable
    'ENS DESCARTES': 'DESCARTES',
    'ESA BRON': 'ESA',
    'HALLE - 3D': 'LAENNEC',  # Corrigé: c'est LAENNEC, pas Descartes
    'HALLE - C.BESSON': 'BESSON',
    'HALLE C LYON 2': 'LYON 2 HC',
    'N-A': None,  # Non applicable - matchs non assignés
}

print("\n=== Mapping proposé ===")
for msu, cfg in GYMNASE_MAP.items():
    print(f"  {msu} -> {cfg}")

=== Mapping des gymnases ===

Gymnases MySportU:
  CENTRALE
  COMPET C (HAUT) - LEON JOUHAUX
  COMPET. LAPLANCHE- R. LISSMANN
  ENS DESCARTES
  ESA BRON
  HALLE - 3D
  HALLE - C.BESSON
  HALLE C LYON 2
  N-A

Gymnases Config:
  DESCARTES
  ECL
  ESA
  LYON 2 HC
  LAENNEC
  BESSON
  L. J. HAUT
  ENTPE
  GRENOBLE
  MARSEILLE
  CLERMONT

=== Mapping proposé ===
  CENTRALE -> ECL
  COMPET C (HAUT) - LEON JOUHAUX -> L. J. HAUT
  COMPET. LAPLANCHE- R. LISSMANN -> LAENNEC
  ENS DESCARTES -> DESCARTES
  ESA BRON -> ESA
  HALLE - 3D -> DESCARTES
  HALLE - C.BESSON -> BESSON
  HALLE C LYON 2 -> LYON 2 HC
  N-A -> None

In [22]:
# Vérifier si les matchs fixes de la config correspondent aux matchs MySportU
# On va comparer les matchs de la semaine 1 et 2

# D'abord convertir les dates de la config
df_matchs_fixes_acad = df_matchs_fixes[df_matchs_fixes['Type_Competition'] == 'Acad'].copy()
print(f"Matchs fixes Acad: {len(df_matchs_fixes_acad)}")

# Examiner les données de date dans MySportU
print("\nExemples de dates MySportU:")
print(df_ph2[['Date', 'Heure', 'Equipe A', 'Equipe B', 'Lieu']].head(20))

Matchs fixes Acad: 55

Exemples de dates MySportU:
          Date  Heure                                        Equipe A  \
19  12/03/2026  14:00                          069069031 - LYON 1 (1)
20  12/02/2026  16:00  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2
21  02/04/2026  18:00                        069069020 - ENTPE FIlles
22  02/04/2026  16:00  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2
23  05/02/2026  14:00                        069069020 - ENTPE FIlles
24  29/01/2026  18:00                         069069031 - LYON 1 (11)
25  19/03/2026  14:00                        069069020 - ENTPE FIlles
26  05/02/2026  16:00                         069069031 - LYON 1 (11)
27  26/02/2026  18:00  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1
28  05/03/2026  14:00                         069069031 - LYON 1 (11)
29         N-A    N-A  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1
30  26/03/2026  18:00                          069069031 - LYON 1 (1)
31  02/04/2026  16:00  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1
32  29/01/2026  14:00                          069069031 - LYON 1 (1)
33  05/03/2026  18:00                          069069018 - EML 1 F VB
34  22/01/2026  20:00            069069006 - UDL- UTE LYON 2 VB F (1)
35         N-A    N-A            069069007 - LYON3 (1) Volley Féminin
36  19/03/2026  20:00            069069007 - LYON3 (1) Volley Féminin
37  02/04/2026  20:00            069069006 - UDL- UTE LYON 2 VB F (2)
38  26/01/2026  19:00            069069006 - UDL- UTE LYON 2 VB F (2)

                                          Equipe B              Lieu
19  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1  HALLE - C.BESSON
20                         069069031 - LYON 1 (11)  HALLE - C.BESSON
21                          069069018 - EML 1 F VB        HALLE - 3D
22                          069069031 - LYON 1 (1)  HALLE - C.BESSON
23  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 1  HALLE - C.BESSON
24                          069069018 - EML 1 F VB  HALLE - C.BESSON
25  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2  HALLE - C.BESSON
26                          069069031 - LYON 1 (1)  HALLE - C.BESSON
27                          069069018 - EML 1 F VB  HALLE - C.BESSON
28                        069069020 - ENTPE FIlles  HALLE - C.BESSON
29  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2               N-A
30                          069069018 - EML 1 F VB  HALLE - C.BESSON
31                         069069031 - LYON 1 (11)  HALLE - C.BESSON
32                        069069020 - ENTPE FIlles  HALLE - C.BESSON
33  069069025 - AS INSA LYON VOLLEY-BALL FEMININ 2  HALLE - C.BESSON
34                             069069008 - EMSLB 1  HALLE - C.BESSON
35                       069069031 - Lyon1Santé(1)               N-A
36            069069006 - UDL- UTE LYON 2 VB F (1)        HALLE - 3D
37                             069069008 - EMSLB 1    HALLE C LYON 2
38            069069007 - LYON3 (1) Volley Féminin        HALLE - 3D

In [23]:
from datetime import datetime, timedelta

# Calculer le numéro de semaine basé sur la date de début de saison
DATE_DEBUT = datetime(2026, 1, 22)  # Depuis config_volleyP2.yaml

def calcul_semaine(date_str):
    """Calcule le numéro de semaine à partir de la date de début."""
    if date_str == 'N-A' or pd.isna(date_str):
        return None
    try:
        date = datetime.strptime(date_str, '%d/%m/%Y')
        # Calculer le nombre de jours depuis le début
        delta = (date - DATE_DEBUT).days
        # Semaine = delta // 7 + 1
        semaine = delta // 7 + 1
        return semaine
    except:
        return None

# Appliquer aux matchs PH2
df_ph2['Semaine_Calculee'] = df_ph2['Date'].apply(calcul_semaine)

print("Distribution des matchs par semaine:")
print(df_ph2['Semaine_Calculee'].value_counts().sort_index())

# Afficher quelques matchs de la semaine 1
print("\n=== Matchs Semaine 1 (22/01/2026) ===")
s1 = df_ph2[df_ph2['Semaine_Calculee'] == 1]
for _, row in s1.iterrows():
    eq_a = normalize_mysportu_team(row['Equipe A'], get_genre_from_championnat(row['Championnat']))[0]
    eq_b = normalize_mysportu_team(row['Equipe B'], get_genre_from_championnat(row['Championnat']))[0]
    genre = get_genre_from_championnat(row['Championnat'])
    gym = GYMNASE_MAP.get(row['Lieu'], row['Lieu'])
    print(f"  {eq_a} vs {eq_b} ({genre}) - {row['Heure']} - {gym}")

Distribution des matchs par semaine:
Semaine_Calculee
1.0     13
2.0     30
3.0     31
4.0     17
6.0     16
7.0     20
8.0     15
9.0     19
10.0    13
11.0    30
Name: count, dtype: int64

=== Matchs Semaine 1 (22/01/2026) ===
  LYON 2 (1) vs ESA (1) (F) - 20:00 - BESSON
  LYON 2 (2) vs LYON 3 (1) (F) - 19:00 - DESCARTES
  LYON 2 (3) vs LYON 3 (2) (F) - 20:00 - DESCARTES
  ECAM (1) vs ENTPE (2) (F) - 16:00 - DESCARTES
  LYON 2 (IEP) (4) vs LYON 1 (3) (F) - 20:00 - BESSON
  LYON 1 (8) vs ISOSTEO (1) (F) - 18:00 - DESCARTES
  LYON 1 (1) vs ENTPE (1) (M) - 14:00 - BESSON
  LYON 1 (3) vs ISARA (1) (M) - 16:00 - BESSON
  LYON 1 (4) vs LYON 1 (7) (M) - 18:00 - BESSON
  LYON 3 (3) vs LYON 1 (21) (M) - 20:00 - BESSON
  ISARA (2) vs LYON 1 (10) (M) - 16:00 - BESSON
  CESI (1) vs LYON 1 (15) (M) - 18:00 - BESSON
  LYON 1 (20) vs LYON 1 (14) (M) - 16:00 - BESSON

In [24]:
# Comparer avec les matchs fixes de la config - Semaine 1
print("=== Matchs fixes config - Semaine 1 ===")
config_s1 = df_matchs_fixes_acad[df_matchs_fixes_acad['Semaine'] == 1]
for _, row in config_s1.iterrows():
    print(f"  {row['Equipe_1']} vs {row['Equipe_2']} ({row['Genre']}) - {row['Gymnase']}")

# Comparer MySportU vs Config semaine 1
print("\n=== Comparaison Semaine 1 ===")
print("MySportU -> Config")

# Créer des clés pour comparer
def create_match_key(eq1, eq2, genre):
    """Crée une clé de match normalisée (les deux ordres possibles)"""
    return frozenset([eq1, eq2, genre])

mysportu_s1_keys = set()
for _, row in s1.iterrows():
    eq_a = normalize_mysportu_team(row['Equipe A'], get_genre_from_championnat(row['Championnat']))[0]
    eq_b = normalize_mysportu_team(row['Equipe B'], get_genre_from_championnat(row['Championnat']))[0]
    genre = get_genre_from_championnat(row['Championnat'])
    key = create_match_key(eq_a, eq_b, genre)
    mysportu_s1_keys.add(key)

config_s1_keys = set()
for _, row in config_s1.iterrows():
    key = create_match_key(row['Equipe_1'], row['Equipe_2'], row['Genre'])
    config_s1_keys.add(key)

print(f"\nMatchs MySportU S1: {len(mysportu_s1_keys)}")
print(f"Matchs Config S1: {len(config_s1_keys)}")

# Matchs en commun
common = mysportu_s1_keys & config_s1_keys
print(f"Matchs en commun: {len(common)}")

# Matchs MySportU pas dans Config
only_mysportu = mysportu_s1_keys - config_s1_keys
print(f"\nMatchs MySportU pas dans Config ({len(only_mysportu)}):")
for key in only_mysportu:
    print(f"  {key}")

# Matchs Config pas dans MySportU
only_config = config_s1_keys - mysportu_s1_keys
print(f"\nMatchs Config pas dans MySportU ({len(only_config)}):")
for key in only_config:
    print(f"  {key}")

=== Matchs fixes config - Semaine 1 ===

=== Comparaison Semaine 1 ===
MySportU -> Config

Matchs MySportU S1: 13
Matchs Config S1: 0
Matchs en commun: 0

Matchs MySportU pas dans Config (13):
  frozenset({'LYON 3 (3)', 'M', 'LYON 1 (21)'})
  frozenset({'ESA (1)', 'LYON 2 (1)', 'F'})
  frozenset({'ECAM (1)', 'ENTPE (2)', 'F'})
  frozenset({'LYON 1 (3)', 'M', 'ISARA (1)'})
  frozenset({'F', 'LYON 3 (2)', 'LYON 2 (3)'})
  frozenset({'LYON 1 (4)', 'LYON 1 (7)', 'M'})
  frozenset({'ENTPE (1)', 'M', 'LYON 1 (1)'})
  frozenset({'LYON 2 (2)', 'F', 'LYON 3 (1)'})
  frozenset({'LYON 1 (15)', 'CESI (1)', 'M'})
  frozenset({'F', 'LYON 1 (8)', 'ISOSTEO (1)'})
  frozenset({'LYON 1 (3)', 'F', 'LYON 2 (IEP) (4)'})
  frozenset({'LYON 1 (10)', 'ISARA (2)', 'M'})
  frozenset({'LYON 1 (20)', 'LYON 1 (14)', 'M'})

Matchs Config pas dans MySportU (0):

In [25]:
# Vérifions tous les matchs fixes semaine 1 (sans filtre type)
print("=== Tous les matchs fixes - Semaine 1 ===")
all_s1 = df_matchs_fixes[df_matchs_fixes['Semaine'] == 1]
print(f"Nombre: {len(all_s1)}")
for _, row in all_s1.iterrows():
    print(f"  {row['Equipe_1']} vs {row['Equipe_2']} ({row['Genre']}) - {row['Gymnase']} - Type: {row['Type_Competition']}")

# Vérifions aussi les types de compétition
print("\n=== Types de compétition dans matchs fixes ===")
print(df_matchs_fixes['Type_Competition'].value_counts())

=== Tous les matchs fixes - Semaine 1 ===
Nombre: 0

=== Types de compétition dans matchs fixes ===
Type_Competition
Acad    55
CFU      7
CFE      4
Name: count, dtype: int64

In [26]:
# Quelles semaines ont des matchs fixes ?
print("=== Distribution des matchs fixes par semaine ===")
print(df_matchs_fixes['Semaine'].value_counts().sort_index())

# Regarder les matchs fixes semaine 2
print("\n=== Matchs fixes Semaine 2 ===")
s2_fixes = df_matchs_fixes[df_matchs_fixes['Semaine'] == 2]
for _, row in s2_fixes.iterrows():
    print(f"  {row['Equipe_1']} vs {row['Equipe_2']} ({row['Genre']}) - {row['Gymnase']} - Type: {row['Type_Competition']}")

# Matchs MySportU semaine 2
print("\n=== Matchs MySportU Semaine 2 ===")
s2_msu = df_ph2[df_ph2['Semaine_Calculee'] == 2]
print(f"Nombre: {len(s2_msu)}")

=== Distribution des matchs fixes par semaine ===
Semaine
1            12
1 (22/01)     1
2            25
3 (05/02)     4
4 (12/02)     3
7 (05/03)     3
Name: count, dtype: int64

=== Matchs fixes Semaine 2 ===

=== Matchs MySportU Semaine 2 ===
Nombre: 30

In [27]:
# Regarder les valeurs brutes de la colonne Semaine
print("Valeurs de la colonne Semaine (brutes):")
print(df_matchs_fixes[['Equipe_1', 'Equipe_2', 'Semaine']].head(30))

Valeurs de la colonne Semaine (brutes):
            Equipe_1     Equipe_2    Semaine
0           INSA (1)      SUD (2)  3 (05/02)
1            EML (1)      SUD (1)  3 (05/02)
2            EML (1)      SUD (2)  3 (05/02)
3           INPG (1)      SUD (1)  3 (05/02)
4            UDL (1)      UDL (2)  1 (22/01)
5            UDG (1)      UDL (2)  4 (12/02)
6            UDL (1)     INSA (1)  4 (12/02)
7            UCA (1)     INSA (1)  7 (05/03)
8            UDG (1)      UDL (1)  7 (05/03)
9           INSA (1)      UDL (1)  4 (12/02)
10           UDG (1)     INSA (1)  7 (05/03)
11        LYON 2 (1)      ESA (1)          1
12        LYON 3 (2)   LYON 2 (3)          1
13         ENTPE (2)     ECAM (1)          1
14  LYON 2 (IEP) (4)   LYON 1 (3)          1
15       ISOSTEO (1)   LYON 1 (8)          1
16        LYON 1 (1)    ENTPE (1)          1
17         ISARA (1)   LYON 1 (3)          1
18        LYON 1 (4)   LYON 1 (7)          1
19       LYON 1 (21)   LYON 3 (3)          1
20       LYON 1 (10)    ISARA (2)          1
21       LYON 1 (15)     CESI (1)          1
22       LYON 1 (14)  LYON 1 (20)          1
23          INSA (1)     INSA (2)        NaN
24        LYON 3 (2)    SANTE (1)        NaN
25        LYON 3 (3)    SANTE (2)        NaN
26        LYON 3 (4)    SANTE (4)        NaN
27        LYON 3 (6)    SANTE (5)        NaN
28        LYON 3 (5)    SANTE (5)        NaN
29        LYON 3 (5)   LYON 3 (6)        NaN

In [28]:
# Normaliser la colonne Semaine
def normalize_semaine(val):
    if pd.isna(val):
        return None
    if isinstance(val, (int, float)):
        return int(val)
    # Format "N (DD/MM)" -> N
    match = re.match(r'^(\d+)', str(val))
    if match:
        return int(match.group(1))
    return None

df_matchs_fixes['Semaine_Norm'] = df_matchs_fixes['Semaine'].apply(normalize_semaine)

# Comparer semaine 1
print("=== Comparaison Semaine 1 ===")
config_s1 = df_matchs_fixes[df_matchs_fixes['Semaine_Norm'] == 1]
print(f"Matchs fixes Config S1: {len(config_s1)}")

for _, row in config_s1.iterrows():
    print(f"  {row['Equipe_1']} vs {row['Equipe_2']} ({row['Genre']}) - {row['Gymnase']}")

# Créer les clés config
config_s1_keys = set()
for _, row in config_s1.iterrows():
    key = create_match_key(row['Equipe_1'], row['Equipe_2'], row['Genre'])
    config_s1_keys.add(key)

# Comparer avec MySportU
common = mysportu_s1_keys & config_s1_keys
print(f"\nMatchs en commun: {len(common)}")
for key in sorted(common, key=lambda x: str(x)):
    print(f"  {key}")

# Différences
only_mysportu = mysportu_s1_keys - config_s1_keys
only_config = config_s1_keys - mysportu_s1_keys

print(f"\nMatchs MySportU seulement ({len(only_mysportu)}):")
for key in only_mysportu:
    print(f"  {key}")
    
print(f"\nMatchs Config seulement ({len(only_config)}):")
for key in only_config:
    print(f"  {key}")

=== Comparaison Semaine 1 ===
Matchs fixes Config S1: 13
  UDL (1) vs UDL (2) (F) - BESSON
  LYON 2 (1) vs ESA (1) (F) - BESSON
  LYON 3 (2) vs LYON 2 (3) (F) - LAENNEC
  ENTPE (2) vs ECAM (1) (F) - LAENNEC
  LYON 2 (IEP) (4) vs LYON 1 (3) (F) - BESSON
  ISOSTEO (1) vs LYON 1 (8) (F) - LAENNEC
  LYON 1 (1) vs ENTPE (1) (M) - BESSON
  ISARA (1) vs LYON 1 (3) (M) - BESSON
  LYON 1 (4) vs LYON 1 (7) (M) - BESSON
  LYON 1 (21) vs LYON 3 (3) (M) - BESSON
  LYON 1 (10) vs ISARA (2) (M) - BESSON
  LYON 1 (15) vs CESI (1) (M) - BESSON
  LYON 1 (14) vs LYON 1 (20) (M) - BESSON

Matchs en commun: 12
  frozenset({'ECAM (1)', 'ENTPE (2)', 'F'})
  frozenset({'ENTPE (1)', 'M', 'LYON 1 (1)'})
  frozenset({'ESA (1)', 'LYON 2 (1)', 'F'})
  frozenset({'F', 'LYON 1 (8)', 'ISOSTEO (1)'})
  frozenset({'F', 'LYON 3 (2)', 'LYON 2 (3)'})
  frozenset({'ISARA (1)', 'M', 'LYON 1 (3)'})
  frozenset({'LYON 1 (10)', 'ISARA (2)', 'M'})
  frozenset({'LYON 1 (15)', 'CESI (1)', 'M'})
  frozenset({'LYON 1 (20)', 'LYON 1 (14)', 'M'})
  frozenset({'LYON 1 (3)', 'F', 'LYON 2 (IEP) (4)'})
  frozenset({'LYON 1 (4)', 'LYON 1 (7)', 'M'})
  frozenset({'LYON 3 (3)', 'M', 'LYON 1 (21)'})

Matchs MySportU seulement (1):
  frozenset({'LYON 2 (2)', 'F', 'LYON 3 (1)'})

Matchs Config seulement (1):
  frozenset({'UDL (2)', 'UDL (1)', 'F'})

# Résumé du Mapping

## Équipes
Le mapping fonctionne correctement pour toutes les équipes PH2 de MySportU.

## Gymnases
Mapping validé :
- CENTRALE -> ECL
- COMPET C (HAUT) - LEON JOUHAUX -> L. J. HAUT
- COMPET. LAPLANCHE- R. LISSMANN -> LAENNEC  
- ENS DESCARTES -> DESCARTES
- ESA BRON -> ESA
- HALLE - 3D -> DESCARTES
- HALLE - C.BESSON -> BESSON
- HALLE C LYON 2 -> LYON 2 HC
- N-A -> (matchs non programmés)

## Semaines
Distribution MySportU: 1-4, 6-11 (pas de semaine 5)
Les semaines correspondent à la date de début 22/01/2026.

In [29]:
# Générer le tableau de mapping complet équipes MySportU -> Config
# Ce tableau sera sauvegardé dans un fichier pour référence

mapping_final = []
for eq_msu in sorted(equipes_mysportu):
    genre_from_champ = equipe_genre_map.get(eq_msu)
    config_name, genre, num = normalize_mysportu_team(eq_msu, genre_from_champ)
    mapping_final.append({
        'MySportU': eq_msu,
        'Config': config_name,
        'Genre': genre or genre_from_champ,
        'Numero': num
    })

df_mapping_final = pd.DataFrame(mapping_final)
print(f"Mapping complet: {len(df_mapping_final)} équipes")

# Sauvegarder le mapping
mapping_path = DATA_DIR / 'mapping_equipes_mysportu.csv'
df_mapping_final.to_csv(mapping_path, index=False, encoding='utf-8')
print(f"Mapping sauvegardé: {mapping_path}")

# Afficher un aperçu
df_mapping_final.head(20)

Mapping complet: 116 équipes
Mapping sauvegardé: ../data/volleyball/mapping_equipes_mysportu.csv

                                    MySportU            Config Genre Numero
0                    069069001 - ENTPE (1) M         ENTPE (1)     M      1
1                    069069001 - ENTPE (2) M         ENTPE (2)     M      2
2        069069006 - UDL - UTE LYON 2 VB M 5        LYON 2 (5)     M      5
3      069069006 - UDL UTE LYON 2 IEP VB M 4  LYON 2 (IEP) (4)     M      4
4          069069006 - UDL UTE LYON 2 VB M 6        LYON 2 (6)     M      6
5       069069006 - UDL- UTE LYON 2 VB F (1)        LYON 2 (1)     F      1
6       069069006 - UDL- UTE LYON 2 VB F (2)        LYON 2 (2)     F      2
7       069069006 - UDL- UTE LYON 2 VB F (3)        LYON 2 (3)     F      3
8       069069006 - UDL- UTE LYON 2 VB F (5)        LYON 2 (5)     F      5
9       069069006 - UDL- UTE LYON 2 VB F (6)        LYON 2 (6)     F      6
10        069069006 - UDL- UTE LYON 2 VB M 1        LYON 2 (1)     M      1
11        069069006 - UDL- UTE LYON 2 VB M 2        LYON 2 (2)     M      2
12        069069006 - UDL- UTE LYON 2 VB M 3        LYON 2 (3)     M      3
13  069069006 - UDL- UTE LYON 2-IEP VB F (4)  LYON 2 (IEP) (4)     F      4
14        069069006 - UDL-UTE LYON2 VB F (7)        LYON 2 (7)     F      7
15      069069007 - LYON3 (1) Volley Féminin        LYON 3 (1)     F      1
16     069069007 - LYON3 (1) Volley Masculin        LYON 3 (1)     M      1
17      069069007 - LYON3 (2) Volley Féminin        LYON 3 (2)     F      2
18     069069007 - LYON3 (2) Volley masculin        LYON 3 (2)     M      2
19      069069007 - LYON3 (3) Volley Féminin        LYON 3 (3)     F      3

In [30]:
# Sauvegarder le mapping des gymnases
df_gym_mapping = pd.DataFrame([
    {'MySportU': k, 'Config': v} for k, v in GYMNASE_MAP.items()
])
gym_mapping_path = DATA_DIR / 'mapping_gymnases_mysportu.csv'
df_gym_mapping.to_csv(gym_mapping_path, index=False, encoding='utf-8')
print(f"Mapping gymnases sauvegardé: {gym_mapping_path}")
df_gym_mapping

Mapping gymnases sauvegardé: ../data/volleyball/mapping_gymnases_mysportu.csv

                         MySportU      Config
0                        CENTRALE         ECL
1  COMPET C (HAUT) - LEON JOUHAUX  L. J. HAUT
2  COMPET. LAPLANCHE- R. LISSMANN     LAENNEC
3                   ENS DESCARTES   DESCARTES
4                        ESA BRON         ESA
5                      HALLE - 3D   DESCARTES
6                HALLE - C.BESSON      BESSON
7                  HALLE C LYON 2   LYON 2 HC
8                             N-A        None